version: "3.8"

services:
  gewechat:
    image: registry.cn-chengdu.aliyuncs.com/tu1h/wechotd:alpine
    container_name: gewe
    restart: always
    ports:
      - "2531:2531"
      - "2532:2532"
    volumes:
      - ./gewechat_data:/root/temp
    privileged: true
